# Generated by Django 4.1.3 on 2022-11-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='myApp/static/components/')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('order', models.CharField(max_length=25)),
                ('value', models.TextField(blank=True)),
                ('javascript', models.TextField(blank=True)),
                ('data', models.DateField(blank=True)),
                ('color', models.CharField(choices=[('nav', 'nav'), ('cards', 'cards'), ('alerts', 'alerts'), ('coin', 'coin')], default='green', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('html', models.TextField(blank=True)),
                ('modal', models.TextField(blank=True)),
                ('user', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='myApp/static/tags/')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('paragraph', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=250, unique=True)),
                ('full_name', models.CharField(max_length=250, unique=True)),
                ('image', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('key', models.TextField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('data', models.DateField(blank=True)),
            ],
        ),
    ]
